// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

#pragma warning disable S103 // Lines should not be too long
[assembly: SuppressMessage("Major Code Smell", "S109:Magic numbers should not be used", Justification = "Autogenerated file by EntityFramework", Scope = "namespaceanddescendants", Target = "~N:AutoHub.DataAccess.Migrations")]
[assembly: SuppressMessage("Major Code Smell", "S109:Magic numbers should not be used", Justification = "Setting ID`s, creating constants for it will be redundant.", Scope = "namespaceanddescendants", Target = "~N:AutoHub.DataAccess.EntitySettings")]
#pragma warning restore S103 // Lines should not be too long
